package com.silouder.app.model

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector

data class NatureAvatar(
    val id: String,
    val name: String,
    val icon: ImageVector,
    val tintColor: Color,
    val bgGradientColor: Color
)

object NatureAvatars {
    val ALL = listOf(
        NatureAvatar(
            id = "mountain",
            name = "Mountain Peak",
            icon = Icons.Filled.Terrain,
            tintColor = Color(0xFF38BDF8),
            bgGradientColor = Color(0xFF0C4A6E)
        ),
        NatureAvatar(
            id = "forest",
            name = "Pine Forest",
            icon = Icons.Filled.Forest,
            tintColor = Color(0xFF10B981),
            bgGradientColor = Color(0xFF064E3B)
        ),
        NatureAvatar(
            id = "waves",
            name = "Ocean Waves",
            icon = Icons.Filled.Waves,
            tintColor = Color(0xFF00E5FF),
            bgGradientColor = Color(0xFF083344)
        ),
        NatureAvatar(
            id = "sunrise",
            name = "Sunrise Dawn",
            icon = Icons.Filled.WbSunny,
            tintColor = Color(0xFFF59E0B),
            bgGradientColor = Color(0xFF78350F)
        ),
        NatureAvatar(
            id = "leaf",
            name = "Autumn Leaf",
            icon = Icons.Filled.Eco,
            tintColor = Color(0xFFF97316),
            bgGradientColor = Color(0xFF7C2D12)
        ),
        NatureAvatar(
            id = "aurora",
            name = "Aurora Glow",
            icon = Icons.Filled.AutoAwesome,
            tintColor = Color(0xFFA855F7),
            bgGradientColor = Color(0xFF581C87)
        ),
        NatureAvatar(
            id = "water_drop",
            name = "Water Droplet",
            icon = Icons.Filled.WaterDrop,
            tintColor = Color(0xFF06B6D4),
            bgGradientColor = Color(0xFF164E63)
        ),
        NatureAvatar(
            id = "storm",
            name = "Thunder Storm",
            icon = Icons.Filled.Thunderstorm,
            tintColor = Color(0xFFEAB308),
            bgGradientColor = Color(0xFF422006)
        ),
        NatureAvatar(
            id = "desert",
            name = "Desert Dune",
            icon = Icons.Filled.Landscape,
            tintColor = Color(0xFFD97706),
            bgGradientColor = Color(0xFF451A03)
        ),
        NatureAvatar(
            id = "volcano",
            name = "Volcanic Lava",
            icon = Icons.Filled.LocalFireDepartment,
            tintColor = Color(0xFFEF4444),
            bgGradientColor = Color(0xFF7F1D1D)
        ),
        NatureAvatar(
            id = "glacier",
            name = "Glacier Frost",
            icon = Icons.Filled.AcUnit,
            tintColor = Color(0xFF67E8F9),
            bgGradientColor = Color(0xFF155E75)
        ),
        NatureAvatar(
            id = "bamboo",
            name = "Bamboo Grove",
            icon = Icons.Filled.Spa,
            tintColor = Color(0xFF84CC16),
            bgGradientColor = Color(0xFF365314)
        )
    )

    fun getById(id: String): NatureAvatar {
        return ALL.find { it.id == id } ?: ALL.first()
    }
}

data class UserProfile(
    val displayName: String = "Alpine Echo",
    val customNumberOrTag: String = "#7721",
    val bioStatus: String = "Decentralized • Off-Grid • Forward Secret",
    val avatarId: String = "mountain",
    val isAutoGenerated: Boolean = true,
    val joinedTimestamp: Long = System.currentTimeMillis()
)
